feat: event processor
axelarnetwork/sentinel pull request #10
Opened 2023-01-11 06:34 UTC by sammy1991106

## Description

## Todos

- [ ] Unit tests
- [ ] Manual tests
- [ ] Documentation
- [ ] Connect epics/issues
- [ ] Tag type of change

## Steps to Test

## Expected Behaviour

## Other Notes

2023-01-14 00:44 UTC, cgorenflo requested changes

2023-01-14 00:44 UTC, cgorenflo commented on src/event_processor.rs
> +        }
```suggestion
        select! {
            result = try_join_all(handles) =>
                result
                    .into_report()
                    .change_context(EventProcessorError::EventHandlerJoinError)?
                    .into_iter()
                    .find(Result::is_err)
                    .unwrap_or(Ok(()))
            ,
            _ = &mut self.close_rx => {
                Ok(())
            },
        }
```

2023-01-14 00:44 UTC, cgorenflo commented on src/event_processor.rs
> +                Some(Err(err)) => {
where is the Option(Result(_)) wrapping coming from? shouldn't it be Option(Event)?

2023-01-14 00:44 UTC, cgorenflo commented on src/event_processor.rs
> +                    }
I suggest to internalize this so it's impossible (make `handle` a nop if called with the wrong event) so it's impossible to accidentally call it when it shouldn't be called

2023-01-14 00:44 UTC, cgorenflo commented on src/event_processor.rs
> +fn new_task<E: 'static>(
can't we just use `stream.map(_)` instead of having this complicated task struct?

2023-01-14 00:44 UTC, cgorenflo commented on src/event_processor.rs
> +    type Err;
constrain the type?

2023-01-14 00:44 UTC, cgorenflo commented on src/event_processor.rs
> +    pub fn add_handler<E: 'static>(
why does this need to be static?

2023-01-19 19:09 UTC, cgorenflo commented on src/event_processor.rs
> +    EventHandlerJoinError,
what is this? can we merge it into the EventHandlerError?

2023-01-19 19:15 UTC, cgorenflo commented on src/event_processor.rs
> +fn new_task<E>(handler: Box<dyn EventHandler<Err = E> + Send + Sync>, mut event_stream: BroadcastStream<Event>) -> Task
```suggestion
fn consume_events<E>(mut event_stream: BroadcastStream<Event>, handler: Box<dyn EventHandler<Err = E> + Send + Sync>) -> Task
```

2023-01-19 19:15 UTC, cgorenflo commented on src/event_processor.rs
> +                .change_context(EventProcessorError::EventHandlerError)?;
love it

2023-01-19 19:25 UTC, sammy1991106 commented on src/event_processor.rs
> +    EventHandlerJoinError,
It's for when the task panics and when it is cancelled. It probably can be merged with `EventHandlerError` but I am not so sure. Your thinking?

2023-01-19 19:45 UTC, cgorenflo approved these changes

2023-01-19 19:51 UTC, merged